Implemented slack login
dailybruin/internal.gallery-maker pull request #11
Opened 2021-02-10 01:41 UTC by ethankeshishian

User is prompted to log in when first accessing the website. After logging in with Slack, the user is redirected to the main homepage. 

Notes:
* Make sure to update the frontend with npm run build. 
* Make sure to update the .env file with the new slack variable.

2021-02-11 01:10 UTC, DumboOctopus requested changes
Hi guys! Overall it looks pretty solid. I made some comments on things I think need some refactoring/cleanup. If you wanna discuss any of them, feel free to just message me on slack!

After we resolve all the comments in this review, you can push your modified branch to github and it will automatically update the pull request. Then I'll take another look at it and make sure to run and test some edge cases. If I find anything sus, I'll let you guys know and we can work it out. Otherwise, I'll approve the request and you guys can click the honrary green merge button

2021-02-11 01:10 UTC, DumboOctopus commented on react/src/components/Gallery/index.js
> +class Gallery extends React.Component {
is this component still used?

2021-02-11 01:10 UTC, DumboOctopus commented on django_project/django_project/settings.py
> +else:
with this, you don't have to have the if statement because we don't really have a default value like we do for SECRET_KEY.  If the person doesn't provide a key, the system should just fail. So you could simplify it to
```
SLACK_SECRET_KEY = os.environ.get('SLACK_SECRET_KEY')
```

2021-02-11 01:10 UTC, DumboOctopus commented on django_project/oauth/views.py
> +
And you can ask me for examples of how to log if need be

2021-02-11 01:10 UTC, DumboOctopus commented on react/src/components/Home/index.js
> +  console.log('props.isLoggedIn', props.isLoggedIn);
be sure to remove these debugging statements as well

2021-02-13 03:10 UTC, ethankeshishian commented on react/src/components/Gallery/index.js
> +class Gallery extends React.Component {
Not sure, we didn't make any changes here.

2021-02-13 03:14 UTC, ethankeshishian commented on django_project/oauth/views.py
> +            new_user = User.objects.create_user(username=userId, password='')
Looks like slack returns the whole name as a string. Not sure if we can parse this if names aren't always one word for the first and one for the last name?

2021-02-14 05:27 UTC, DumboOctopus commented on react/src/components/Gallery/index.js
> +class Gallery extends React.Component {
hmm ok could you delete this file then

2021-02-14 05:28 UTC, DumboOctopus commented on django_project/oauth/views.py
> +            new_user = User.objects.create_user(username=userId, password='')
ohh I see. Hmm in that case we can just not do that for now

2021-03-01 23:46 UTC, aritramullick commented on django_project/oauth/views.py
> +    r = requests.post(url = API_ENDPOINT, data = data)
Added try-catch to this block.

2021-03-02 00:17 UTC, aritramullick commented on django_project/oauth/views.py
> +            new_user = User.objects.create_user(username=userId, password='')
So, I found a way to get the User's name. However, I think we might run into some issues if we try to save it as first name and last name (not all users will have exactly 2 words in their name - they could have middle names, or they could use only one nickname for Slack). So, for now, I am saving it as first_name in the User profile only. It should be easy to modify if we want to make changes later!

2021-03-02 00:44 UTC, aritramullick commented on django_project/oauth/views.py
> +def get_logged_in(request):
I think this code has changed a bit, so I am unsure about what to do.

2021-03-03 23:23 UTC, DumboOctopus approved these changes
There just some dead code but besides that it looks good! So I'm gonna approve it. Please do remove these lines (just so the code stays clean). After thats done, feel free to merge!

2021-03-31 16:59 UTC, aritramullick commented on react/src/components/App.js
>          <Route path="/rearrange" component={RearrangeImages} />
Solving this would just be moving the rearrange path above the '/' path?

2021-03-31 17:00 UTC, aritramullick commented on react/package.json
> +    "react-upload-gallery": "^0.2.0",
How so? Do we not still need react-slack-login when a new user tries to sign in?

2021-03-31 17:14 UTC, merged

2021-03-31 20:50 UTC, DumboOctopus commented on react/package.json
> +    "react-upload-gallery": "^0.2.0",
I don't think so just because we are not using the slack react sign in button in the frontend anymore; instead we are using just an `a` tag i think.