backend and frontend support for big centered stream layout
dailybruin/internal.gallery-maker pull request #26
Opened 2021-04-21 07:28 UTC by lishamohan

- added "big-centered-stream" layout choice to gallery model, "big-centered-photo" type choice to image model, and validation function to image serializer to make sure image types line up with gallery layout
- added type selector to caption form
- fixed bug where "are you sure you want to leave" warning shows up after hitting submit button
- note: had to change the max length of layout and type fields in gallery and image models to accommodate the new choices

2021-04-21 20:47 UTC, DumboOctopus requested changes
Looks great! its good that you made the separate constants which stored the human friendly version and keep track of which image types are associated with each gallery layout.

There is one small thing with the names of the fields and another question regarding the `validate` method. 

Lastly, there was a possible inconvenience to the user. Lets say I have an existing gallery with layout = alt. This gallery has a ton of images with their type = alt-image. If I change the layout of the gallery to big centered stream, then all the images still have type = alt-image. Then if I press save, it will fail. This will probably be a bit confusing to the user since they won't realize they need to change the type field for each image when they change the layout. So I think we will need to address this issue somehow. One possible way is automatically changing the type fields when the layout field changes. Another way is providing some error message on the page that has the fields.

2021-04-21 20:47 UTC, DumboOctopus commented on django_project/galleries/serializers.py
> +        if data['type'] not in galleryOptions[data['gallery'].layout]:
do we need to call the super class's version of validate in here?

2021-04-21 20:47 UTC, DumboOctopus commented on django_project/galleries/serializers.py
> +        if data['type'] not in galleryOptions[data['gallery'].layout]:
(I actually forgot so this is actually a question, not a rhetorical question)

2021-04-21 20:47 UTC, DumboOctopus commented on react/src/components/CreateUpdateGallery/index.js
> +    }
oh nice thanks for fixing this bug along with it!

2021-04-21 23:29 UTC, lishamohan commented on django_project/galleries/models.py
> +    BIG_CENTERED_PHOTO = 'big-centered-photo'
Oh yeah I thought it was that too but in #gallery-maker-dev Tommy said it was "big-centered-photo"; should I ask him to confirm?

2021-04-21 23:30 UTC, lishamohan commented on django_project/galleries/serializers.py
> +        if data['type'] not in galleryOptions[data['gallery'].layout]:
Ooh good point -- I don't think so, since they don't do that here https://www.django-rest-framework.org/api-guide/serializers/#object-level-validation

2021-04-22 00:35 UTC, lishamohan commented
Okay I made it so it changes the image types when the user changes the gallery layout. I also adding a loading spinner to the select images page because I noticed the WP endpoint takes a while

2021-04-23 15:56 UTC, DumboOctopus approved these changes
Looks great feel free to merge!

2021-04-23 18:07 UTC, merged