Backend functionality for allowing galleries for add textbox
dailybruin/internal.gallery-maker pull request #27
Opened 2021-05-01 12:51 UTC by changyang-liu

2021-05-01 19:59 UTC, DumboOctopus requested changes
Looks great! Just some small things and edge cases  for the `get_images_and_text`. But I think even as it is now, I think its good enough to give to ethan for his frontend code.


Checks:
1. mainsite endpoint is still the same
2. Couple of edge cases tests for the mainsite endpoint

2021-05-01 19:59 UTC, DumboOctopus commented on django_project/galleries/views.py
> +# @login_required
what was the purpose of removing login required?

2021-05-01 19:59 UTC, DumboOctopus commented on django_project/galleries/serializers.py
> +    while i < len(image_data) + len(textfield_data):
There is an error if the gallery ends with a text field.

2021-05-02 04:37 UTC, changyang-liu commented on django_project/galleries/views.py
> +# @login_required
Oops! I removed it for debugging purposes but forgot to add it back in.

2021-05-02 04:38 UTC, changyang-liu commented on django_project/galleries/serializers.py
> +    while i < len(image_data) + len(textfield_data):
Oh right I forgot to add a check for the index out of range. I'll add it in

2021-05-04 01:29 UTC, DumboOctopus approved these changes
Looks good. I'll press merge

2021-05-04 01:30 UTC, merged